from pydantic import BaseModel, Field


class ResumeChatRequest(BaseModel):
    user_id: str = Field(..., description="The unique identifier of the user.")
    question: str = Field(..., description="The question asked by the user.")


class ResumeChatResponse(BaseModel):
    answer: str
    email: str
    phone: str
    city: str
    # current_weather: str


class ResumeLLMResponse(BaseModel):
    response_text: str = Field(..., description="The response generated by the LLM.")
    contact_email: str = Field(
        ..., description="The contact email provided in the response."
    )
    contact_phone: str = Field(
        ..., description="The contact phone number provided in the response."
    )
    contact_city: str = Field(
        ..., description="The city most worked in provided in the response."
    )
    # current_weather: str = Field(
    #     ..., description="Current weather in the contact city"
    # )
